FORMAT: 1A
HOST: http://orders.apiblueprint.org/

# orders

## Orders Collection [/orders]

### List All Orders [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "product": "Pica",
                "price": {
                    "amount": 4.18,
                    "currency": "EUR"
                },
                "user": {
                    "first_name": "Trevor",
                    "last_name": "Kirkland"
                },
                "status": "new",
                "created_at": 1462365852
            },
            {
                "id": 2,
                "product": "Pica + Sprite",
                "price": {
                    "amount": 2.8,
                    "currency": "EUR"
                },
                "user": {
                    "first_name": "Hunter",
                    "last_name": "Valenzuela"
                },
                "status": "new",
                "created_at": 1462321012
            },
            {
                "id": 3,
                "product": "Mėsainis",
                "price": {
                    "amount": 4.89,
                    "currency": "USD"
                },
                "user": {
                    "first_name": "Imani",
                    "last_name": "House"
                },
                "status": "accepted",
                "created_at": 1462354537
            },
            {
                "id": 4,
                "product": "Submarinas",
                "price": {
                    "amount": 4.34,
                    "currency": "EUR"
                },
                "user": {
                    "first_name": "Casey",
                    "last_name": "Nielsen"
                },
                "status": "accepted",
                "created_at": 1462329737
            },
            {
                "id": 5,
                "product": "Sriuba",
                "price": {
                    "amount": 2.82,
                    "currency": "EUR"
                },
                "user": {
                    "first_name": "Kelly",
                    "last_name": "Crane"
                },
                "status": "accepted",
                "created_at": 1462359516
            },
            {
                "id": 6,
                "product": "Kepta duona",
                "price": {
                    "amount": 3.1,
                    "currency": "EUR"
                },
                "user": {
                    "first_name": "Vladimir",
                    "last_name": "Townsend"
                },
                "status": "accepted",
                "created_at": 1462376839
            },
            {
                "id": 7,
                "product": "Sprite",
                "price": {
                    "amount": 2.06,
                    "currency": "EUR"
                },
                "user": {
                    "first_name": "Trevor",
                    "last_name": "Mosley"
                },
                "status": "new",
                "created_at": 1462334725
            },
            {
                "id": 8,
                "product": "Cepelinai",
                "price": {
                    "amount": 3.47,
                    "currency": "EUR"
                },
                "user": {
                    "first_name": "Christian",
                    "last_name": "Mcknight"
                },
                "status": "accepted",
                "created_at": 1462357077
            },
            {
                "id": 9,
                "product": "Kebabas",
                "price": {
                    "amount": 3.98,
                    "currency": "EUR"
                },
                "user": {
                    "first_name": "Edan",
                    "last_name": "Molina"
                },
                "status": "new",
                "created_at": 1462323906
            },
            {
                "id": 10,
                "product": "Dvi picos",
                "price": {
                    "amount": 4.37,
                    "currency": "USD"
                },
                "user": {
                    "first_name": "Teegan",
                    "last_name": "Owen"
                },
                "status": "new",
                "created_at": 1462346860
            },
            {
                "id": 11,
                "product": "Didelė pica",
                "price": {
                    "amount": 3.95,
                    "currency": "EUR"
                },
                "user": {
                    "first_name": "Holmes",
                    "last_name": "Hampton"
                },
                "status": "new",
                "created_at": 1462357574
            },
            {
                "id": 12,
                "product": "Ledai",
                "price": {
                    "amount": 1.19,
                    "currency": "EUR"
                },
                "user": {
                    "first_name": "Elton",
                    "last_name": "Johnson"
                },
                "status": "new",
                "created_at": 1462349082
            },
            {
                "id": 13,
                "product": "Pica + Alus",
                "price": {
                    "amount": 3.69,
                    "currency": "EUR"
                },
                "user": {
                    "first_name": "Portia",
                    "last_name": "Moon"
                },
                "status": "accepted",
                "created_at": 1462372712
            },
            {
                "id": 14,
                "product": "Karameliniai ledai",
                "price": {
                    "amount": 1.55,
                    "currency": "USD"
                },
                "user": {
                    "first_name": "Alana",
                    "last_name": "Cherry"
                },
                "status": "new",
                "created_at": 1462368417
            },
            {
                "id": 15,
                "product": "Šaltibarščiai",
                "price": {
                    "amount": 2.49,
                    "currency": "EUR"
                },
                "user": {
                    "first_name": "Casey",
                    "last_name": "Franklin"
                },
                "status": "new",
                "created_at": 1462333013
            },
            {
                "id": 16,
                "product": "Ledai",
                "price": {
                    "amount": 1.31,
                    "currency": "EUR"
                },
                "user": {
                    "first_name": "Xenos",
                    "last_name": "Carpenter"
                },
                "status": "new",
                "created_at": 1462327107
            }
        ]

## Order [/order/{order_id}/accept]

+ Parameters
    + order_id (number) - ID of the Order in the form of an integer

### Accept Order [POST]

+ Response 200 (application/json)